export const SET_NAV_INDEX = 'SET_NAV_INDEX'
export const SET_DRAWER_LOCKMODE = 'SET_DRAWER_LOCKMODE'
export const SET_PAGE_LOADING = 'SET_PAGE_LOADING'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS'
export const LOGOUT = 'LOGOUT'
